project_id = "jxxspcwknbeqnwwzjkew"

[auth]
# Disable email confirmation for new signups
enable_signup = true
enable_confirmations = false
# Auto-confirm users on signup
enable_email_autoconfirm = true